### ISSUE TITLE
Make compatible with apiary's snowcrash/drafter

### ISSUE THREAD

**Issue by ghost** [slang800/tidy-markdown#14]
Currently, tidy-markdown imposes a tab length of 2 spaces (I believe), and that causes an [API Blueprint](https://github.com/apiaryio/api-blueprint) file to throw a ton of warnings when run through [drafter](https://github.com/apiaryio/drafter).

```shell
warn dangling message-body asset, expected a pre-formatted code block, 
indent every of it's line by 8 spaces or 2 tabs
```

I'm not sure if it's some expectation of their parser, or something related to this linter, but it would be amazing to have tidy-markdown (specifically, when used with atom-beautify) lint my file and have it be clean when going through the parser.

**Comment by slang800** [comment]
I don't know about drafter, or why it doesn't like a 2-space indent. As for code blocks, we denote those with 3 backticks. But anyway, this user seems to be dead... if anyone else runs into this issue, feel free to comment/reopen.
