### ISSUE TITLE
list after text doesn't work in redcarpet

### ISSUE THREAD

**Issue by phil-opp** [slang800/tidy-markdown#15]
The following empty line seems to be required by redcarpet and kramdown but gets removed by tidy-markdown:

```
Some text block with an enumeration:

- First
- Second
```

Without the empty line it looks like this on Github Pages:

Some text block with an enumeration: - First - Second

**Comment by sebw** [comment]
I have exactly the same problem with [Wikitten](https://github.com/victorstanciu/Wikitten).

**Comment by ChrisChinchilla** [comment]
Same, I was wondering if this was a markdown standard that these renderers ignore, but I've not come across anything that does render lists 'fixed' by tidy-markdown, so maybe not…

How could we fix this? I'm happy to give it a go.

**Comment by slang800** [comment]
should be fixed in #26
