### ISSUE TITLE
After # of headings a space should be added

### ISSUE THREAD

**Issue by rugk** [slang800/tidy-markdown#19]
`#headline` should be converted to `# headline` - otherwise this can also cause some other issues if empty lines after or before an heading are missing.

For more information here is a gif created by using Atom 1.0.15 with [atom-tidy-markdown](https://github.com/slang800/atom-tidy-markdown):
![mdtest](https://cloud.githubusercontent.com/assets/11966684/10054660/9c94d2bc-6232-11e5-9e38-53c72c091983.gif)

**Comment by slang800** [comment]
I'm not sure if `#headline` is ever a valid header... I think it just gets parsed as a paragraph, which we wouldn't want to screw with, just in case there's a valid reason to start a paragraph with a `#` followed by a non-space character.

For example, I'd like `#tbt is the most popular hashtag on Instagram.` to remain a valid paragraph, rather than being turned into a header.

**Comment by rugk** [comment]
Okay, indeed `#text` could be a valid start of a paragraph - did not thought about it.

However on GitHub the space after `#`is not required: https://gist.github.com/rugk/36ab8925c52acdd83d50

See also:
https://github.com/atom/markdown-preview/issues/293
http://johnmacfarlane.net/babelmark2/?text=%23Bad+heading%0A%0A%23+Good+heading

**Comment by rugk** [comment]
So there was already much discussion about this... 

And I also like [this perspective](https://github.com/Galadirith/markdown-preview-plus/issues/88#issuecomment-137351168) - you don't always write the md yourself.
So if you get a badly md file (without these spaces) and quickly want to clean it up it get's messy as you can see in the gif above.

So probably it would be good to have an algorithm to find out whether an `#` without a space is a headline or a paragraph. I mean even if it is only based on the character count (or whether there are  spaces in it)...

**Comment by slang800** [comment]
Oh, you're right - marked must have changed without releasing a new major version :angry:. We actually have tests to ensure that those headers are fixed, and they're broken now.

**Comment by rugk** [comment]
> marked must have changed without releasing a new major version

Marked is the library you use for parsing?
In this case you maybe should remind them of http://semver.org/. :smile:
