### ISSUE TITLE
Use HTTP git remote

### ISSUE THREAD

**Issue by palonsoro** [slang800/tidy-markdown#23]
Hello.

I am trying to install your extension but I must use an HTTP proxy to reach the internet. However, when I try to install your extension, it tries to clone `git://github.com/slang800/tidy-markdown.git`, which is not possible behind a proxy.

Would it be possible to use `http://` instead of `git://`? Most other Atom extensions do it this way and everything works fine (once I properly setup proxy configuration at my workstation).

Thanks in advance

**Comment by palonsoro** [comment]
Sorry, I think I opened the issue in the wrong repo.

**Comment by slang800** [comment]
(moved to https://github.com/slang800/atom-tidy-markdown/issues/32)
