### ISSUE TITLE
/usr/bin/env: node: No such file or directory

### ISSUE THREAD

**Issue by shawnhcorey** [slang800/tidy-markdown#36]
Isn't `node` now called `nodejs`?

Affect file: /usr/local/lib/node_modules/tidy-markdown/bin/index.js

**Comment by slang800** [comment]
```
[slang@fjord ~]$ which node
/usr/bin/node
[slang@fjord ~]$ node -v
v6.3.1
[slang@fjord ~]$ uname -a
Linux fjord 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux
```

I don't think so... what distro are you running on and what command did you use to produce that error?

**Comment by shawnhcorey** [comment]
`$ uname -a
Linux sage 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ echo "# a header #" | tidy-markdown
/usr/bin/env: node: No such file or directory
$ `

But if I link `nodejs` as `node`.

`$ sudo ln -s /usr/bin/nodejs /usr/bin/node
$ echo "# a header #" | tidy-markdown
# a header
$ 
`

**Comment by shawnhcorey** [comment]
An added note: it seems that `nodejs` calls itself `node`. I wish there was some consistency. :(

```sh
$ nodejs --help
Usage: node [options] [ -e script | script.js ] [arguments] 
       node debug script.js [arguments] 

Options:
  -v, --version        print node's version
  -e, --eval script    evaluate script
  -p, --print          evaluate script and print result
  -i, --interactive    always enter the REPL even if stdin
                       does not appear to be a terminal
  --no-deprecation     silence deprecation warnings
  --trace-deprecation  show stack traces on deprecations
  --v8-options         print v8 command line options
  --max-stack-size=val set max v8 stack size (bytes)

Environment variables:
NODE_PATH              ':'-separated list of directories
                       prefixed to the module search path.
NODE_MODULE_CONTEXTS   Set to 1 to load modules in their own
                       global contexts.
NODE_DISABLE_COLORS    Set to 1 to disable colors in the REPL

Documentation can be found at http://nodejs.org/
$ 
```

**Comment by slang800** [comment]
Ah, this seems to be a Ubuntu/Debian-specific thing. See: https://stackoverflow.com/questions/18130164/nodejs-vs-node-on-ubuntu-12-04 (quick solution to your problem) & http://debian.2.n7.nabble.com/Node-js-and-it-s-future-in-debian-td1042211.html (longer discussion) & https://github.com/nodejs/node-v0.x-archive/issues/3911 (another issue about this)

I would change it to work with Ubuntu, but then I'd break it for everyone else:

```
$ stat /usr/bin/nodejs
stat: cannot stat '/usr/bin/nodejs': No such file or directory
```

The underlying issue is that there's some ham-radio package called `node` that was made before nodejs and now there's a naming conflict because names are hard.

**Comment by shawnhcorey** [comment]
It would be part of the install process to determine if it was `node` or `nodejs`. :)

And the ham-radio package has changed it's name, and its `node` should be going away tho I don't know when, :?
