### ISSUE TITLE
Email addresses being converted to mailto: links

### ISSUE THREAD

**Issue by gvanderest** [slang800/tidy-markdown#41]
I'm not entirely sure if I'm correct here, but I typed: `<email@address.com>` and it got converted to `[email@address.com](mailto:email@address.com)` which I just double-checked might not be correct.

Reference: https://daringfireball.net/projects/markdown/syntax (search for "@" for the email address examples)

I was looking through the code and couldn't find the specific case where tidy-markdown is causing this to occur, otherwise I'd have tried to make a pull request for you.

**Comment by slang800** [comment]
yeah, that happens because we compile to HTML and then convert back, so we just didn't have handling for that case, but it's fixed now.
