### ISSUE TITLE
How can I personally DISABLE filter: 'img' from converters.coffee

### ISSUE THREAD

**Issue by graphicsminded** [slang800/tidy-markdown#55]
How can I personally DISABLE filter: 'img' from converters.coffee so my Atom doesn't smash my `<img>` tags when I hit save? 

I'm sorry but I don't see a "How to Customize your tidy-markdown" section.

Your code in your [converters.coffee](https://github.com/slang800/tidy-markdown/blob/master/src/converters.coffee)

```
{
    filter: 'img'
    surroundingBlankLines: false
    replacement: (content, node, links) ->
      alt = getAttribute(node, 'alt') or ''
      url = getAttribute(node, 'src') or ''
      title = getAttribute(node, 'title')
      referenceLink = _.find(links, {url, title})
      if referenceLink
        if alt.toLowerCase() is referenceLink.name
          "![#{alt}]"
        else
          "![#{alt}][#{referenceLink.name}]"
      else if title
        "![#{alt}](#{url} \"#{title}\")"
      else
        "![#{alt}](#{url})"
  }
```

I just want to disable this somehow in Atom so I can commit `<img>` tags to my README.md file.

Can I disable just this this one filter or do I have to turn off tidy-markdown all together?

Thanks,
Scott

**Comment by slang800** [comment]
Oh, it's supposed to be as non-customizable as possible. What do you want `<img>` tags for?

**Comment by graphicsminded** [comment]
Thanks for responding. I am using <img> tags in the README.md so that I may set a `style="max-width:200px;"` inside the tag, otherwise the image looks like [this](https://github.com/graphicsminded/mod_qr_code_link#qr-code-link-joomla-3x-module).

When I want it to look like [this](https://github.com/graphicsminded/mod_qr_code_link/blob/3bba8a1e5b77eb9e1158af3081a9db2ac90679d5/README.md#qr-code-link-joomla-3x-module).

Is there any way I can turn off just that one filter without having to completely disable tidy-markdown?

Thanks,
Scott

**Comment by slang800** [comment]
Oh, we should just detect whether or not the tag has important attributes like `width`/`height` and disable it that way. Then we don't need any configuration and it does basically what anyone would expect - convert HTML to markdown, but not fundamentally change the structure of the document.
