### ISSUE TITLE
Support for numeric lists

### ISSUE THREAD

**Issue by Glavin001** [slang800/tidy-markdown#7]
## Input

```markdown
- item
-  item
-   item

1. one
2.  two
2.   three
```

## Preview

- item
-  item
-   item

1. one
2.  two
2.   three

## Expected Output

```markdown
- item
- item
- item

1. one
2. two
2. three
```

## Current (wrong) Output

```markdown
- item
- item
- item
- one
- two
- three
```

Notice how it removes the list item's numbering (1,2,3.).

/cc https://github.com/Glavin001/atom-beautify/issues/292

**Comment by slang800** [comment]
hmm... that's pretty weird, but I'm not sure if it's tidy-markdown. it might be [marked](https://github.com/chjj/marked), or an edge case with the markdown language.

a quick test with atom's markdown preview shows this:

![screenshot from 2015-04-30 11 57 11](https://cloud.githubusercontent.com/assets/1049204/7416874/629102d6-ef30-11e4-9f4f-fe9ac43a0785.png)

and the same issue appears with this input:

```markdown
- item
- item
- item

1. one
2. two
3. three
```

**Comment by Glavin001** [comment]
Yup! Right on. See this issue for Marked: https://github.com/chjj/marked/issues/55

Basically, it treats it as a single list, since there is no header or any text separating the two lists.
So by adding a heading or text, it works!

### Input 

```markdown
   # heading 1

- item
-  item
-   item

 ## heading 2
 
1. one
2.  two
2.   three
```

### Output

This works!

```markdown
# heading 1
- item
- item
- item

## heading 2
1. one
2. two
3. three
```

Gorgeous.

**Comment by slang800** [comment]
thanks for finding that - I think I'm going to enable smart-lists and/or switch to a common-markdown compliant parser, since marked [doesn't really follow any standard](https://github.com/chjj/marked/issues/563).
